version: '3.7'
services:
  mongodb_container:
    image: mongo:latest
    container_name: mongodb_container
    environment:
      MONGO_INITDB_DATABASE: facebook
      MONGO_INITDB_ROOT_USERNAME: elya_data
      MONGO_INITDB_ROOT_PASSWORD: elya_data
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
    networks: 
      - scraper_network
  

  scraper:
    build: .
    command: bash -c "uvicorn service.app:app --host 0.0.0.0 --port 8008 --reload"
    ports:
      - "8008:8008"    
    depends_on: 
      - mongodb_container
    networks: 
      - scraper_network


networks: 
  scraper_network:
volumes:
  mongodb_data_container:
    
